-- MySQL Script generated by MySQL Workbench
-- 01/31/19 11:53:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ms_account_db
-- -----------------------------------------------------
-- 账户数据库

-- -----------------------------------------------------
-- Schema ms_account_db
--
-- 账户数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ms_account_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema ms_storage_db
-- -----------------------------------------------------
-- 商品库存数据库

-- -----------------------------------------------------
-- Schema ms_storage_db
--
-- 商品库存数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ms_storage_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema ms_order_db
-- -----------------------------------------------------
-- 订单数据库

-- -----------------------------------------------------
-- Schema ms_order_db
--
-- 订单数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ms_order_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ms_account_db` ;

-- -----------------------------------------------------
-- Table `ms_account_db`.`ms_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ms_account_db`.`ms_account` ;

CREATE TABLE IF NOT EXISTS `ms_account_db`.`ms_account` (
  `user_id` INT NOT NULL COMMENT '用户ID',
  `balance` DECIMAL(11,2) NOT NULL DEFAULT 0.0 COMMENT '余额',
  `frozen` DECIMAL(11,2) NOT NULL DEFAULT 0.0 COMMENT '冻结金额',
  `version` INT NOT NULL DEFAULT 0 COMMENT '版本号',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

USE `ms_storage_db` ;

-- -----------------------------------------------------
-- Table `ms_storage_db`.`ms_storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ms_storage_db`.`ms_storage` ;

CREATE TABLE IF NOT EXISTS `ms_storage_db`.`ms_storage` (
  `commodity_id` INT NOT NULL COMMENT '商品ID',
  `count` INT NOT NULL DEFAULT 0 COMMENT '库存数量',
  `version` INT NOT NULL DEFAULT 0 COMMENT '版本号',
  PRIMARY KEY (`commodity_id`))
ENGINE = InnoDB;

USE `ms_order_db` ;

-- -----------------------------------------------------
-- Table `ms_order_db`.`ms_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ms_order_db`.`ms_order` ;

CREATE TABLE IF NOT EXISTS `ms_order_db`.`ms_order` (
  `user_id` INT NOT NULL COMMENT '用户ID',
  `commodity_id` INT NOT NULL COMMENT '商品ID',
  `count` INT NOT NULL DEFAULT 0 COMMENT '商品数量',
  `money` DECIMAL(11,2) NOT NULL DEFAULT 0 COMMENT '成交金额',
  `trade_time` INT NOT NULL DEFAULT 0 COMMENT '成交时间（秒数）',
  `version` INT NOT NULL DEFAULT 0 COMMENT '版本号',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
